import type { Metadata } from "next";
import Image from "next/image";
import { Braces, CircuitBoard, Cog, Cuboid, Radio, Smartphone } from "lucide-react";
import { PageHero } from "@/components/sections/page-hero";
import { ContactCta } from "@/components/sections/contact-cta";
import { SectionHeading } from "@/components/ui/section-heading";

export const metadata: Metadata = { title: "STEM & Robotics", description: "Practical engineering and technology education for schools, organisations and young innovators." };
const subjects = [{ icon: CircuitBoard, title: "Electronics" }, { icon: Cog, title: "Arduino & robotics" }, { icon: Braces, title: "Programming" }, { icon: Smartphone, title: "MIT App Inventor" }, { icon: Cuboid, title: "3D printing & design" }, { icon: Radio, title: "IoT & connected systems" }];
export default function StemPage() { return <><PageHero eyebrow="STEM & robotics" title="Learning technology by building with it." description="Hands-on engineering education for Primary, JHS and SHS learners, including students who have recently completed school." image="/images/stem-robotics/robotics-learning.jpg" imageAlt="Black students assembling an electronics project in an Accra classroom" /><section className="section"><div className="container"><div className="split-heading"><SectionHeading eyebrow="What learners explore" title="Skills grow through real projects." /><p>Learners do more than watch a demonstration. They solve problems, handle components and build projects suited to their age, experience and available time.</p></div><div className="subject-grid">{subjects.map(({ icon: Icon, title }) => <div key={title}><Icon aria-hidden="true" strokeWidth={1.5} /><h3>{title}</h3></div>)}</div></div></section><section className="program section section--soft"><div className="program__grid container"><div className="program__image"><Image fill sizes="(max-width: 800px) 100vw, 50vw" src="/images/stem-robotics/student-electronics.jpg" alt="Black student working on a laptop during a technology lesson" /></div><div><SectionHeading eyebrow="For schools & organisations" title="A program built around your learners." /><ol><li><span>01</span><div><h3>Get to know the learners</h3><p>We discuss their level, your goals and the time available.</p></div></li><li><span>02</span><div><h3>Plan the sessions</h3><p>We choose the right concepts, materials and projects for the group.</p></div></li><li><span>03</span><div><h3>Learn by building</h3><p>Learners make, test, troubleshoot and explain their own work.</p></div></li></ol></div></div></section><ContactCta title="Would you like your learners to experience engineering first-hand?" /></> }
